-- Auto-generated DynamoDB migration seed
-- Source table: scorchbook-ffcf7631-tastings
-- Generated by scripts/migrate-dynamo.sh
-- Idempotent: uses ON CONFLICT DO NOTHING.

BEGIN;

-- =============================================================
-- JIT user creation for each unique createdBy (Cognito sub)
-- =============================================================

INSERT INTO users (id, email, display_name, created_at)
VALUES (gen_random_uuid(), 'migrated-user-1@tastebase.ahara.io', 'Migrated User', now())
ON CONFLICT (email) DO NOTHING;

INSERT INTO cognito_users (cognito_sub, user_id, email, linked_at)
SELECT '6438f4b8-10f1-7090-35e3-440090018320', u.id, 'migrated-user-1@tastebase.ahara.io', now()
FROM users u WHERE u.email = 'migrated-user-1@tastebase.ahara.io'
ON CONFLICT (cognito_sub) DO NOTHING;

-- =============================================================
-- Tasting records
-- =============================================================

INSERT INTO tastings (
  id, user_id, product_type, name, maker, date, score, style,
  heat_user, heat_vendor, refreshing, sweet,
  tasting_notes_user, tasting_notes_vendor, product_url,
  image_url, image_key,
  ingredients_image_url, ingredients_image_key,
  nutrition_image_url, nutrition_image_key,
  nutrition_facts, ingredients,
  voice_key, voice_transcript,
  status, processing_error, needs_attention, attention_reason,
  created_at, updated_at
)
SELECT
  '3706e664-50d6-49dc-a47c-58b20afcfdac'::uuid,
  cu.user_id,
  'drink'::product_type,
  'Mountain Ginger',
  'Brew Dr.',
  '2026-01-10'::date,
  5,
  'Kombucha',
  3,
  NULL,
  NULL,
  NULL,
  '- Flavor: Good ginger flavor
- Sweetness: A little bit too sweet
- Refreshing: Not very refreshing',
  '',
  '',
  'https://scorchbook-ffcf7631-media.s3.amazonaws.com/images/3706e664-50d6-49dc-a47c-58b20afcfdac-1768075008182.jpeg',
  'images/3706e664-50d6-49dc-a47c-58b20afcfdac-1768075008182.jpeg',
  'https://scorchbook-ffcf7631-media.s3.amazonaws.com/images/3706e664-50d6-49dc-a47c-58b20afcfdac-ingredients-1768080653054.jpeg',
  'images/3706e664-50d6-49dc-a47c-58b20afcfdac-ingredients-1768080653054.jpeg',
  'https://scorchbook-ffcf7631-media.s3.amazonaws.com/images/3706e664-50d6-49dc-a47c-58b20afcfdac-nutrition-1768080653184.jpeg',
  'images/3706e664-50d6-49dc-a47c-58b20afcfdac-nutrition-1768080653184.jpeg',
  '{}'::jsonb,
  ARRAY['Brewed Tea','Water','Green Tea','Turmeric Root','Black Pepper','Cane Sugar','Ginger Juice','Live Kombucha Culture (Yeast, Bacteria)','Turmeric Juice','Citric Acid','Ginger Extract']::text[],
  'voice/3706e664-50d6-49dc-a47c-58b20afcfdac-1768075008305.webm',
  'Uh, a decent kombucha, probably a 5 out of 10. Good ginger flavor, a little bit too sweet for me, probably, uh, uh, 3 out of 5 on the sweetness. And because of that sweetness in the ginger, it''s probably only a 2 out of 5 on the refreshing. But, uh, it''s good more as a, uh, nice slow drink. Uh, mostly ginger comes through, um, a little bit of the turmeric, not too much tea or fruit or anything like that.',
  'complete'::processing_status,
  NULL,
  FALSE,
  NULL,
  '2026-01-10T19:56:48.162Z'::timestamptz,
  '2026-01-10T21:32:15.804Z'::timestamptz
FROM cognito_users cu
WHERE cu.cognito_sub = '6438f4b8-10f1-7090-35e3-440090018320'
ON CONFLICT (id) DO NOTHING;

INSERT INTO tastings (
  id, user_id, product_type, name, maker, date, score, style,
  heat_user, heat_vendor, refreshing, sweet,
  tasting_notes_user, tasting_notes_vendor, product_url,
  image_url, image_key,
  ingredients_image_url, ingredients_image_key,
  nutrition_image_url, nutrition_image_key,
  nutrition_facts, ingredients,
  voice_key, voice_transcript,
  status, processing_error, needs_attention, attention_reason,
  created_at, updated_at
)
SELECT
  'd29939c4-e778-4519-9b01-26a65b466cdc'::uuid,
  cu.user_id,
  'sauce'::product_type,
  'Mo''Rockin Sauce',
  'Urban Pantry',
  '2026-01-10'::date,
  8,
  'Habanero',
  1,
  NULL,
  NULL,
  NULL,
  '- Aroma: Earthy, with notes of cumin and garlic
- Flavor: Powerful lemon, with Middle Eastern spices
- Spice/Heat: Mild, with earthy cumin presence
- Pairings: Pairs well with chicken, vegetables, and lentils',
  '',
  '',
  'https://scorchbook-ffcf7631-media.s3.amazonaws.com/images/d29939c4-e778-4519-9b01-26a65b466cdc-1768072776376.jpeg',
  'images/d29939c4-e778-4519-9b01-26a65b466cdc-1768072776376.jpeg',
  'https://scorchbook-ffcf7631-media.s3.amazonaws.com/images/d29939c4-e778-4519-9b01-26a65b466cdc-ingredients-1768080690854.jpeg',
  'images/d29939c4-e778-4519-9b01-26a65b466cdc-ingredients-1768080690854.jpeg',
  'https://scorchbook-ffcf7631-media.s3.amazonaws.com/images/d29939c4-e778-4519-9b01-26a65b466cdc-nutrition-1768080690977.jpeg',
  'images/d29939c4-e778-4519-9b01-26a65b466cdc-nutrition-1768080690977.jpeg',
  '{"servingSize":"1 tsp (5mL)","calories":5,"totalFat":"0g","sodium":"45mg","totalCarbs":"0g","sugars":"0g","protein":"0g"}'::jsonb,
  ARRAY['water','vinegar','preserved lemon','pure lemon sunflower oil','turmeric','distilled vinegar','ascorbic acid','spices','jalapeno pepper puree','garlic puree','xanthan gum','citric acid']::text[],
  'voice/d29939c4-e778-4519-9b01-26a65b466cdc-1768072776558.webm',
  'Heat, 1 out of 5, taste 8 out of 10, uh, the Middle Eastern flavors come through a little bit. The lemon is, is pretty powerful. Um, I''d call it more earthy than Middle Eastern, probably, uh, definitely get a lot of cumin, uh, garlic though, uh, turmeric, not so much. Uh, would go really good on. Ah, chicken. Uh, vegetables, lentils for sure, probably not fish unless it''s a salmon, um, not red meat or, or pork. I don''t think the lemon would contrast with them too much. Um, overall, uh, pretty, uh, fruity, lingering finish, not too spicy, except for the earthy cumin that comes through.',
  'complete'::processing_status,
  NULL,
  FALSE,
  NULL,
  '2026-01-10T19:19:36.357Z'::timestamptz,
  '2026-01-10T21:32:27.816Z'::timestamptz
FROM cognito_users cu
WHERE cu.cognito_sub = '6438f4b8-10f1-7090-35e3-440090018320'
ON CONFLICT (id) DO NOTHING;

INSERT INTO tastings (
  id, user_id, product_type, name, maker, date, score, style,
  heat_user, heat_vendor, refreshing, sweet,
  tasting_notes_user, tasting_notes_vendor, product_url,
  image_url, image_key,
  ingredients_image_url, ingredients_image_key,
  nutrition_image_url, nutrition_image_key,
  nutrition_facts, ingredients,
  voice_key, voice_transcript,
  status, processing_error, needs_attention, attention_reason,
  created_at, updated_at
)
SELECT
  '1c8cecad-88b1-4584-bf61-1202edf8400e'::uuid,
  cu.user_id,
  'drink'::product_type,
  'Organic Kombucha Cranberry Apple',
  'Simple Truth',
  '2026-01-10'::date,
  9,
  'Kombucha',
  0,
  NULL,
  NULL,
  NULL,
  '- Flavor: Cranberry forward
- Sweetness: Very sweet
- Acidity: Cranberry sour bitterness',
  '',
  'https://www.food4less.com/p/simple-truth-organic-cranberry-apple-kombucha/0001111003882',
  'https://scorchbook-ffcf7631-media.s3.amazonaws.com/images/1c8cecad-88b1-4584-bf61-1202edf8400e-1768021899511.jpeg',
  'images/1c8cecad-88b1-4584-bf61-1202edf8400e-1768021899511.jpeg',
  NULL,
  NULL,
  NULL,
  NULL,
  '{"servingSize":"1 bottle (473)","calories":130}'::jsonb,
  ARRAY['WATER','ORGANIC RAW KOMBUCHA','FILTERED WATER','ORGANIC CANE SUGAR','ORGANIC TEA BLEND','ORGANIC KOMBUCHA CULTURE','APPLE JUICE CONCENTRATE','ORGANIC NATURAL FLAVOR','BACILLUS SUBTILIS (PROBIOTIC)']::text[],
  'voice/1c8cecad-88b1-4584-bf61-1202edf8400e-1768021899698.webm',
  'Uh, taste, 9 out of 10, heat, 0 out of 10, pretty sure it''s not a hot sauce, kombucha. Uh, definitely cranberry forward, very sweet, even though it''s cranberry, um, you can taste so much sugars in there for sure. Um, but it has that nice cranberry sour bitterness. I''d probably put it with dessert mostly though, uh, ice cream, sorbet, maybe like a good raspberry chocolate tart, something like that.',
  'complete'::processing_status,
  NULL,
  FALSE,
  NULL,
  '2026-01-10T05:11:39.509Z'::timestamptz,
  '2026-01-10T21:32:33.365Z'::timestamptz
FROM cognito_users cu
WHERE cu.cognito_sub = '6438f4b8-10f1-7090-35e3-440090018320'
ON CONFLICT (id) DO NOTHING;

INSERT INTO tastings (
  id, user_id, product_type, name, maker, date, score, style,
  heat_user, heat_vendor, refreshing, sweet,
  tasting_notes_user, tasting_notes_vendor, product_url,
  image_url, image_key,
  ingredients_image_url, ingredients_image_key,
  nutrition_image_url, nutrition_image_key,
  nutrition_facts, ingredients,
  voice_key, voice_transcript,
  status, processing_error, needs_attention, attention_reason,
  created_at, updated_at
)
SELECT
  '33864dcc-7248-4190-a4ae-b79c04dc7dac'::uuid,
  cu.user_id,
  'sauce'::product_type,
  'Honey Ginger Hot Sauce',
  'Honey Ginger',
  '2026-01-10'::date,
  7,
  'Ginger',
  2,
  NULL,
  NULL,
  NULL,
  '- Aroma: Quick, bright hit
- Flavor: Ginger and honey balance well
- Sweetness: Not overly sweet
- Spice/Heat: Moderate heat',
  '',
  '',
  'https://scorchbook-ffcf7631-media.s3.amazonaws.com/images/33864dcc-7248-4190-a4ae-b79c04dc7dac-1768074921246.jpeg',
  'images/33864dcc-7248-4190-a4ae-b79c04dc7dac-1768074921246.jpeg',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  'voice/33864dcc-7248-4190-a4ae-b79c04dc7dac-1768074921458.webm',
  'Really surprisingly good hot sauce, uh, probably 2 out of 5 on the heat scale, I''m gonna put it up at a 7 out of 10 on the taste scale. Uh, the, has a quick, uh, bright hit, um, no lingering finish at all. Uh, the honey comes through, but it''s not overly sweet, um, and the ginger really balances that out really well. Um, this would go good on almost any kind of Asian dish, ramen, uh, any of our other kind of noodles, or Uh, fried rice, um, is he doing it on chicken as well for sure, um. Uh, really surprisingly good, uh, huge notes of, of ginger and again the honey without the sweetness.',
  'complete'::processing_status,
  NULL,
  FALSE,
  NULL,
  '2026-01-10T19:55:21.239Z'::timestamptz,
  '2026-01-10T21:32:26.934Z'::timestamptz
FROM cognito_users cu
WHERE cu.cognito_sub = '6438f4b8-10f1-7090-35e3-440090018320'
ON CONFLICT (id) DO NOTHING;

COMMIT;
