# Frontend SPA hosting: S3 + CloudFront + ACM + Route53 + runtime config

locals {
  frontend_bucket = "${local.prefix}-frontend"
  frontend_dir    = "${path.module}/../../frontend/dist"

  site_files = {
    for file in fileset(local.frontend_dir, "**") :
    file => file
    if file != "config.js"
  }

  mime_types = {
    ".html"  = "text/html"
    ".css"   = "text/css"
    ".js"    = "application/javascript"
    ".json"  = "application/json"
    ".svg"   = "image/svg+xml"
    ".png"   = "image/png"
    ".jpg"   = "image/jpeg"
    ".jpeg"  = "image/jpeg"
    ".gif"   = "image/gif"
    ".ico"   = "image/x-icon"
    ".xml"   = "application/xml"
    ".txt"   = "text/plain"
    ".woff"  = "font/woff"
    ".woff2" = "font/woff2"
    ".ttf"   = "font/ttf"
  }

  runtime_config = {
    apiBaseUrl        = "https://${local.api_hostname}"
    cognitoUserPoolId = local.cognito_pool_id
    cognitoClientId   = aws_cognito_user_pool_client.app.id
  }
}

# --- S3 bucket ---

resource "aws_s3_bucket" "frontend" {
  bucket = local.frontend_bucket
}

resource "aws_s3_bucket_public_access_block" "frontend" {
  bucket = aws_s3_bucket.frontend.id

  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

resource "aws_s3_bucket_ownership_controls" "frontend" {
  bucket = aws_s3_bucket.frontend.id

  rule {
    object_ownership = "BucketOwnerPreferred"
  }
}

resource "aws_s3_bucket_policy" "frontend" {
  bucket = aws_s3_bucket.frontend.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Sid    = "AllowCloudFrontServicePrincipal"
        Effect = "Allow"
        Principal = {
          Service = "cloudfront.amazonaws.com"
        }
        Action   = "s3:GetObject"
        Resource = "${aws_s3_bucket.frontend.arn}/*"
        Condition = {
          StringEquals = {
            "AWS:SourceArn" = aws_cloudfront_distribution.frontend.arn
          }
        }
      }
    ]
  })
}

# Upload all built SPA files (excluding config.js which is managed separately)
resource "aws_s3_object" "frontend_files" {
  for_each = local.site_files

  bucket        = aws_s3_bucket.frontend.id
  key           = each.key
  source        = "${local.frontend_dir}/${each.key}"
  source_hash   = filemd5("${local.frontend_dir}/${each.key}")
  content_type  = local.mime_types[regex("\\.[^.]+$", each.key)]
  cache_control = each.key == "index.html" ? "no-cache" : "public, max-age=31536000, immutable"
}

# Runtime config with real Cognito/API values
resource "aws_s3_object" "frontend_config" {
  bucket        = aws_s3_bucket.frontend.id
  key           = "config.js"
  content_type  = "application/javascript"
  cache_control = "no-cache"

  content = <<-EOT
// Auto-generated by Terraform - Do not edit manually
window.__APP_CONFIG__ = Object.assign(window.__APP_CONFIG__ || {}, ${jsonencode(local.runtime_config)});
EOT
}

# --- CloudFront ---

resource "aws_cloudfront_origin_access_control" "frontend" {
  name                              = "${local.prefix}-frontend-oac"
  description                       = "OAC for ${local.frontend_hostname}"
  origin_access_control_origin_type = "s3"
  signing_behavior                  = "always"
  signing_protocol                  = "sigv4"
}

resource "aws_cloudfront_distribution" "frontend" {
  enabled             = true
  is_ipv6_enabled     = true
  default_root_object = "index.html"
  aliases             = [local.frontend_hostname]
  price_class         = "PriceClass_100"

  origin {
    domain_name              = aws_s3_bucket.frontend.bucket_regional_domain_name
    origin_id                = "S3-${local.prefix}-frontend"
    origin_access_control_id = aws_cloudfront_origin_access_control.frontend.id
  }

  default_cache_behavior {
    allowed_methods        = ["GET", "HEAD", "OPTIONS"]
    cached_methods         = ["GET", "HEAD"]
    target_origin_id       = "S3-${local.prefix}-frontend"
    viewer_protocol_policy = "redirect-to-https"
    compress               = true

    forwarded_values {
      query_string = false
      cookies {
        forward = "none"
      }
    }

    min_ttl     = 0
    default_ttl = 3600
    max_ttl     = 86400
  }

  # SPA routing: return index.html for 404/403
  custom_error_response {
    error_code         = 404
    response_code      = 200
    response_page_path = "/index.html"
  }

  custom_error_response {
    error_code         = 403
    response_code      = 200
    response_page_path = "/index.html"
  }

  restrictions {
    geo_restriction {
      restriction_type = "none"
    }
  }

  viewer_certificate {
    acm_certificate_arn      = aws_acm_certificate.frontend.arn
    ssl_support_method       = "sni-only"
    minimum_protocol_version = "TLSv1.2_2021"
  }
}

# --- ACM certificate for frontend ---

resource "aws_acm_certificate" "frontend" {
  domain_name       = local.frontend_hostname
  validation_method = "DNS"

  lifecycle {
    create_before_destroy = true
  }
}

resource "aws_route53_record" "frontend_cert_validation" {
  for_each = {
    for dvo in aws_acm_certificate.frontend.domain_validation_options :
    dvo.domain_name => {
      name  = dvo.resource_record_name
      type  = dvo.resource_record_type
      value = dvo.resource_record_value
    }
  }

  zone_id = nonsensitive(data.aws_ssm_parameter.route53_zone_id.value)
  name    = each.value.name
  type    = each.value.type
  ttl     = 60
  records = [each.value.value]
}

resource "aws_acm_certificate_validation" "frontend" {
  certificate_arn         = aws_acm_certificate.frontend.arn
  validation_record_fqdns = [for r in aws_route53_record.frontend_cert_validation : r.fqdn]
}

# --- DNS ---

resource "aws_route53_record" "frontend" {
  zone_id = nonsensitive(data.aws_ssm_parameter.route53_zone_id.value)
  name    = local.frontend_hostname
  type    = "A"

  alias {
    name                   = aws_cloudfront_distribution.frontend.domain_name
    zone_id                = aws_cloudfront_distribution.frontend.hosted_zone_id
    evaluate_target_health = false
  }
}

resource "aws_route53_record" "frontend_ipv6" {
  zone_id = nonsensitive(data.aws_ssm_parameter.route53_zone_id.value)
  name    = local.frontend_hostname
  type    = "AAAA"

  alias {
    name                   = aws_cloudfront_distribution.frontend.domain_name
    zone_id                = aws_cloudfront_distribution.frontend.hosted_zone_id
    evaluate_target_health = false
  }
}

# --- CloudFront invalidation on content change ---

resource "terraform_data" "frontend_deployment" {
  input = sha256(jsonencode({
    files          = [for k, v in aws_s3_object.frontend_files : v.source_hash]
    runtime_config = local.runtime_config
  }))

  lifecycle {
    action_trigger {
      events  = [after_update]
      actions = [action.aws_cloudfront_create_invalidation.frontend]
    }
  }

  depends_on = [aws_s3_object.frontend_config]
}

action "aws_cloudfront_create_invalidation" "frontend" {
  config {
    distribution_id = aws_cloudfront_distribution.frontend.id
    paths           = ["/*"]
  }
}
