# Frontend hosting: S3 for static assets, OG Lambda for HTML, CloudFront in front

locals {
  frontend_bucket = "${local.prefix}-frontend"
  frontend_dir    = "${path.module}/../../frontend/dist"

  # Exclude index.html — the OG Lambda generates HTML dynamically
  # Exclude config.js — uploaded separately with runtime values
  # Exclude sw.js + manifest.webmanifest — need no-cache for PWA update detection
  pwa_no_cache_files = toset(["config.js", "index.html", "sw.js", "manifest.webmanifest"])

  site_files = {
    for file in fileset(local.frontend_dir, "**") :
    file => file
    if !contains(local.pwa_no_cache_files, file)
  }

  mime_types = {
    ".html"        = "text/html"
    ".css"         = "text/css"
    ".js"          = "application/javascript"
    ".json"        = "application/json"
    ".svg"         = "image/svg+xml"
    ".png"         = "image/png"
    ".jpg"         = "image/jpeg"
    ".jpeg"        = "image/jpeg"
    ".gif"         = "image/gif"
    ".ico"         = "image/x-icon"
    ".xml"         = "application/xml"
    ".txt"         = "text/plain"
    ".woff"        = "font/woff"
    ".woff2"       = "font/woff2"
    ".ttf"         = "font/ttf"
    ".webmanifest" = "application/manifest+json"
  }

  runtime_config = {
    apiBaseUrl        = "https://${local.api_hostname}"
    cognitoUserPoolId = module.ctx.cognito_user_pool_id
    cognitoClientId   = module.cognito_app.client_id
  }

  # Extract hashed entry files from Vite build output
  frontend_js  = one([for f in fileset(local.frontend_dir, "assets/index-*.js") : f])
  frontend_css = one([for f in fileset(local.frontend_dir, "assets/*.css") : f])
}

# --- S3 bucket for static assets ---

resource "aws_s3_bucket" "frontend" {
  bucket = local.frontend_bucket
}

resource "aws_s3_bucket_public_access_block" "frontend" {
  bucket = aws_s3_bucket.frontend.id

  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

resource "aws_s3_bucket_ownership_controls" "frontend" {
  bucket = aws_s3_bucket.frontend.id

  rule {
    object_ownership = "BucketOwnerPreferred"
  }
}

resource "aws_s3_bucket_policy" "frontend" {
  bucket = aws_s3_bucket.frontend.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Sid    = "AllowCloudFrontServicePrincipal"
        Effect = "Allow"
        Principal = {
          Service = "cloudfront.amazonaws.com"
        }
        Action   = "s3:GetObject"
        Resource = "${aws_s3_bucket.frontend.arn}/*"
        Condition = {
          StringEquals = {
            "AWS:SourceArn" = aws_cloudfront_distribution.frontend.arn
          }
        }
      }
    ]
  })
}

# Upload static assets (no index.html — Lambda generates it)
resource "aws_s3_object" "frontend_files" {
  for_each = local.site_files

  bucket        = aws_s3_bucket.frontend.id
  key           = each.key
  source        = "${local.frontend_dir}/${each.key}"
  source_hash   = filemd5("${local.frontend_dir}/${each.key}")
  content_type  = local.mime_types[regex("\\.[^.]+$", each.key)]
  cache_control = "public, max-age=31536000, immutable"
}

# PWA service worker + manifest — must not be cached for update detection
resource "aws_s3_object" "pwa_sw" {
  bucket        = aws_s3_bucket.frontend.id
  key           = "sw.js"
  source        = "${local.frontend_dir}/sw.js"
  source_hash   = filemd5("${local.frontend_dir}/sw.js")
  content_type  = "application/javascript"
  cache_control = "no-cache"
}

resource "aws_s3_object" "pwa_manifest" {
  bucket        = aws_s3_bucket.frontend.id
  key           = "manifest.webmanifest"
  source        = "${local.frontend_dir}/manifest.webmanifest"
  source_hash   = filemd5("${local.frontend_dir}/manifest.webmanifest")
  content_type  = "application/manifest+json"
  cache_control = "no-cache"
}

# Runtime config
resource "aws_s3_object" "frontend_config" {
  bucket        = aws_s3_bucket.frontend.id
  key           = "config.js"
  content_type  = "application/javascript"
  cache_control = "no-cache"

  content = <<-EOT
// Auto-generated by Terraform
window.__APP_CONFIG__ = Object.assign(window.__APP_CONFIG__ || {}, ${jsonencode(local.runtime_config)});
EOT
}

# --- OG Lambda ---

data "archive_file" "og_server" {
  type        = "zip"
  source_file = "${path.module}/../../backend/target/lambda/og-server/bootstrap"
  output_path = "${path.module}/../../backend/target/lambda/og-server/bootstrap.zip"
}

resource "aws_lambda_function" "og_server" {
  function_name = "${local.prefix}-og-server"
  role          = module.api.role_arn
  handler       = "bootstrap"
  runtime       = "provided.al2023"
  architectures = ["x86_64"]
  timeout       = 10
  memory_size   = 256

  filename         = data.archive_file.og_server.output_path
  source_code_hash = data.archive_file.og_server.output_base64sha256

  vpc_config {
    subnet_ids         = module.ctx.private_subnet_ids
    security_group_ids = [module.api.security_group_id]
  }

  environment {
    variables = merge(local.db_env, {
      ENTRY_JS  = "/${local.frontend_js}"
      ENTRY_CSS = "/${local.frontend_css}"
      SITE_URL  = "https://${local.frontend_hostname}"
    })
  }
}

resource "aws_lambda_function_url" "og_server" {
  function_name      = aws_lambda_function.og_server.function_name
  authorization_type = "NONE"
}

# --- CloudFront ---

resource "aws_cloudfront_origin_access_control" "frontend" {
  name                              = "${local.prefix}-frontend-oac"
  description                       = "OAC for ${local.frontend_hostname}"
  origin_access_control_origin_type = "s3"
  signing_behavior                  = "always"
  signing_protocol                  = "sigv4"
}

resource "aws_cloudfront_distribution" "frontend" {
  enabled         = true
  is_ipv6_enabled = true
  aliases         = [local.frontend_hostname]
  price_class     = "PriceClass_100"

  # Origin 1: S3 for static assets
  origin {
    domain_name              = aws_s3_bucket.frontend.bucket_regional_domain_name
    origin_id                = "S3-${local.prefix}-frontend"
    origin_access_control_id = aws_cloudfront_origin_access_control.frontend.id
  }

  # Origin 2: OG Lambda for HTML
  origin {
    domain_name = replace(replace(aws_lambda_function_url.og_server.function_url, "https://", ""), "/", "")
    origin_id   = "Lambda-${local.prefix}-og"

    custom_origin_config {
      http_port              = 80
      https_port             = 443
      origin_protocol_policy = "https-only"
      origin_ssl_protocols   = ["TLSv1.2"]
    }
  }

  # Static assets — immutable cache, S3 origin
  ordered_cache_behavior {
    path_pattern           = "/assets/*"
    allowed_methods        = ["GET", "HEAD"]
    cached_methods         = ["GET", "HEAD"]
    target_origin_id       = "S3-${local.prefix}-frontend"
    viewer_protocol_policy = "redirect-to-https"
    compress               = true

    forwarded_values {
      query_string = false
      cookies { forward = "none" }
    }

    min_ttl     = 31536000
    default_ttl = 31536000
    max_ttl     = 31536000
  }

  # Config.js — no cache
  ordered_cache_behavior {
    path_pattern           = "/config.js"
    allowed_methods        = ["GET", "HEAD"]
    cached_methods         = ["GET", "HEAD"]
    target_origin_id       = "S3-${local.prefix}-frontend"
    viewer_protocol_policy = "redirect-to-https"
    compress               = true

    forwarded_values {
      query_string = false
      cookies { forward = "none" }
    }

    min_ttl     = 0
    default_ttl = 0
    max_ttl     = 300
  }

  # Static files (favicons, social images) — S3 origin
  ordered_cache_behavior {
    path_pattern           = "*.png"
    allowed_methods        = ["GET", "HEAD"]
    cached_methods         = ["GET", "HEAD"]
    target_origin_id       = "S3-${local.prefix}-frontend"
    viewer_protocol_policy = "redirect-to-https"
    compress               = true

    forwarded_values {
      query_string = false
      cookies { forward = "none" }
    }

    min_ttl     = 3600
    default_ttl = 86400
    max_ttl     = 604800
  }

  ordered_cache_behavior {
    path_pattern           = "*.svg"
    allowed_methods        = ["GET", "HEAD"]
    cached_methods         = ["GET", "HEAD"]
    target_origin_id       = "S3-${local.prefix}-frontend"
    viewer_protocol_policy = "redirect-to-https"
    compress               = true

    forwarded_values {
      query_string = false
      cookies { forward = "none" }
    }

    min_ttl     = 3600
    default_ttl = 86400
    max_ttl     = 604800
  }

  ordered_cache_behavior {
    path_pattern           = "*.ico"
    allowed_methods        = ["GET", "HEAD"]
    cached_methods         = ["GET", "HEAD"]
    target_origin_id       = "S3-${local.prefix}-frontend"
    viewer_protocol_policy = "redirect-to-https"
    compress               = true

    forwarded_values {
      query_string = false
      cookies { forward = "none" }
    }

    min_ttl     = 3600
    default_ttl = 86400
    max_ttl     = 604800
  }

  # Service worker — must revalidate every time for PWA updates
  ordered_cache_behavior {
    path_pattern           = "/sw.js"
    allowed_methods        = ["GET", "HEAD"]
    cached_methods         = ["GET", "HEAD"]
    target_origin_id       = "S3-${local.prefix}-frontend"
    viewer_protocol_policy = "redirect-to-https"
    compress               = true

    forwarded_values {
      query_string = false
      cookies { forward = "none" }
    }

    min_ttl     = 0
    default_ttl = 0
    max_ttl     = 0
  }

  # PWA manifest — short cache, needs to stay fresh
  ordered_cache_behavior {
    path_pattern           = "/manifest.webmanifest"
    allowed_methods        = ["GET", "HEAD"]
    cached_methods         = ["GET", "HEAD"]
    target_origin_id       = "S3-${local.prefix}-frontend"
    viewer_protocol_policy = "redirect-to-https"
    compress               = true

    forwarded_values {
      query_string = false
      cookies { forward = "none" }
    }

    min_ttl     = 0
    default_ttl = 0
    max_ttl     = 300
  }

  # Workbox runtime — hashed filename, immutable
  ordered_cache_behavior {
    path_pattern           = "/workbox-*.js"
    allowed_methods        = ["GET", "HEAD"]
    cached_methods         = ["GET", "HEAD"]
    target_origin_id       = "S3-${local.prefix}-frontend"
    viewer_protocol_policy = "redirect-to-https"
    compress               = true

    forwarded_values {
      query_string = false
      cookies { forward = "none" }
    }

    min_ttl     = 31536000
    default_ttl = 31536000
    max_ttl     = 31536000
  }

  # Default: OG Lambda generates HTML with dynamic meta tags
  default_cache_behavior {
    allowed_methods        = ["GET", "HEAD", "OPTIONS"]
    cached_methods         = ["GET", "HEAD"]
    target_origin_id       = "Lambda-${local.prefix}-og"
    viewer_protocol_policy = "redirect-to-https"
    compress               = true

    forwarded_values {
      query_string = false
      cookies { forward = "none" }
    }

    min_ttl     = 0
    default_ttl = 3600
    max_ttl     = 86400
  }

  restrictions {
    geo_restriction {
      restriction_type = "none"
    }
  }

  viewer_certificate {
    acm_certificate_arn      = aws_acm_certificate.frontend.arn
    ssl_support_method       = "sni-only"
    minimum_protocol_version = "TLSv1.2_2021"
  }
}

# --- ACM ---

resource "aws_acm_certificate" "frontend" {
  domain_name       = local.frontend_hostname
  validation_method = "DNS"

  lifecycle {
    create_before_destroy = true
  }
}

resource "aws_route53_record" "frontend_cert_validation" {
  for_each = {
    for dvo in aws_acm_certificate.frontend.domain_validation_options :
    dvo.domain_name => {
      name  = dvo.resource_record_name
      type  = dvo.resource_record_type
      value = dvo.resource_record_value
    }
  }

  zone_id = module.ctx.route53_zone_id
  name    = each.value.name
  type    = each.value.type
  ttl     = 60
  records = [each.value.value]
}

resource "aws_acm_certificate_validation" "frontend" {
  certificate_arn         = aws_acm_certificate.frontend.arn
  validation_record_fqdns = [for r in aws_route53_record.frontend_cert_validation : r.fqdn]
}

# --- DNS ---

resource "aws_route53_record" "frontend" {
  zone_id = module.ctx.route53_zone_id
  name    = local.frontend_hostname
  type    = "A"

  alias {
    name                   = aws_cloudfront_distribution.frontend.domain_name
    zone_id                = aws_cloudfront_distribution.frontend.hosted_zone_id
    evaluate_target_health = false
  }
}

resource "aws_route53_record" "frontend_ipv6" {
  zone_id = module.ctx.route53_zone_id
  name    = local.frontend_hostname
  type    = "AAAA"

  alias {
    name                   = aws_cloudfront_distribution.frontend.domain_name
    zone_id                = aws_cloudfront_distribution.frontend.hosted_zone_id
    evaluate_target_health = false
  }
}

# --- CloudFront invalidation on deploy ---

resource "terraform_data" "frontend_deployment" {
  input = sha256(jsonencode({
    files          = [for k, v in aws_s3_object.frontend_files : v.source_hash]
    runtime_config = local.runtime_config
    entry_js       = local.frontend_js
    entry_css      = local.frontend_css
    sw_hash        = aws_s3_object.pwa_sw.source_hash
    manifest_hash  = aws_s3_object.pwa_manifest.source_hash
  }))

  lifecycle {
    action_trigger {
      events  = [after_update]
      actions = [action.aws_cloudfront_create_invalidation.frontend]
    }
  }

  depends_on = [aws_s3_object.frontend_config]
}

action "aws_cloudfront_create_invalidation" "frontend" {
  config {
    distribution_id = aws_cloudfront_distribution.frontend.id
    paths           = ["/*"]
  }
}
