#!/usr/bin/env bash
set -euo pipefail
# Migrates data from DynamoDB table scorchbook-ffcf7631-tastings into PostgreSQL.
# Uses: aws dynamodb scan, jq
# Outputs: db/migrations/seed/001_migrate_dynamo.sql

DYNAMO_TABLE="${DYNAMO_TABLE:-scorchbook-ffcf7631-tastings}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
OUTPUT_DIR="${ROOT_DIR}/db/migrations/seed"
OUTPUT_FILE="${OUTPUT_DIR}/001_migrate_dynamo.sql"
JQ_SCRIPT="${SCRIPT_DIR}/migrate-dynamo.jq"

mkdir -p "${OUTPUT_DIR}"

echo "Scanning DynamoDB table: ${DYNAMO_TABLE}..."
RAW_JSON=$(aws dynamodb scan --table-name "${DYNAMO_TABLE}" --region us-east-1 --output json)

ITEM_COUNT=$(echo "${RAW_JSON}" | jq '.Items | length')
echo "Found ${ITEM_COUNT} items."

if [[ "${ITEM_COUNT}" -eq 0 ]]; then
  echo "No items found. Exiting."
  exit 0
fi

# Phase 1: Extract unique cognito subs and generate user INSERT statements
echo "Extracting unique users..."
UNIQUE_SUBS=$(echo "${RAW_JSON}" | jq -r '[.Items[] | select(.createdBy.S) | .createdBy.S] | unique | .[]')

{
cat <<'HEADER'
-- Auto-generated DynamoDB migration seed
-- Source table: scorchbook-ffcf7631-tastings
-- Generated by scripts/migrate-dynamo.sh
-- Idempotent: uses ON CONFLICT DO NOTHING.

BEGIN;

-- =============================================================
-- JIT user creation for each unique createdBy (Cognito sub)
-- =============================================================
HEADER

USER_IDX=1
for SUB in ${UNIQUE_SUBS}; do
  SAFE_SUB="${SUB//\'/\'\'}"
  EMAIL="migrated-user-${USER_IDX}@tastebase.ahara.io"
  cat <<EOF

INSERT INTO users (id, email, display_name, created_at)
VALUES (gen_random_uuid(), '${EMAIL}', 'Migrated User', now())
ON CONFLICT (email) DO NOTHING;

INSERT INTO cognito_users (cognito_sub, user_id, email, linked_at)
SELECT '${SAFE_SUB}', u.id, '${EMAIL}', now()
FROM users u WHERE u.email = '${EMAIL}'
ON CONFLICT (cognito_sub) DO NOTHING;
EOF
  USER_IDX=$((USER_IDX + 1))
done

# Phase 2: Generate tasting INSERT statements using jq
echo "${RAW_JSON}" | jq -r -f "${JQ_SCRIPT}"

echo ""
echo "COMMIT;"
} > "${OUTPUT_FILE}"

echo "Migration SQL written to: ${OUTPUT_FILE}"
echo "Review the file, then run:  db-seed"
