#!/usr/bin/env bash
set -euo pipefail
# Migrates data from DynamoDB table scorchbook-ffcf7631-tastings into PostgreSQL.
# Uses: aws dynamodb scan, jq
# Outputs: db/migrations/seed/001_migrate_dynamo.sql

DYNAMO_TABLE="${DYNAMO_TABLE:-scorchbook-ffcf7631-tastings}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
OUTPUT_DIR="${ROOT_DIR}/db/migrations/seed"
OUTPUT_FILE="${OUTPUT_DIR}/001_migrate_dynamo.sql"

mkdir -p "${OUTPUT_DIR}"

echo "Scanning DynamoDB table: ${DYNAMO_TABLE}..."
RAW_JSON=$(aws dynamodb scan --table-name "${DYNAMO_TABLE}" --region us-east-1 --output json)

ITEM_COUNT=$(echo "${RAW_JSON}" | jq '.Items | length')
echo "Found ${ITEM_COUNT} items."

if [[ "${ITEM_COUNT}" -eq 0 ]]; then
  echo "No items found. Exiting."
  exit 0
fi

# Generate the SQL migration file
cat > "${OUTPUT_FILE}" <<'HEADER'
-- Auto-generated DynamoDB migration seed
-- Source table: scorchbook-ffcf7631-tastings
-- Generated by scripts/migrate-dynamo.sh
--
-- This script is idempotent: uses ON CONFLICT DO NOTHING for inserts.

BEGIN;

HEADER

# ---------------------------------------------------------------
# Phase 1: Extract unique createdBy values and create JIT users
# ---------------------------------------------------------------
echo "Extracting unique users..."

# Build a list of unique createdBy (Cognito sub) values
UNIQUE_SUBS=$(echo "${RAW_JSON}" | jq -r '
  [.Items[] | select(.createdBy.S) | .createdBy.S] | unique | .[]
')

USER_IDX=1
declare -A SUB_TO_EMAIL

for SUB in ${UNIQUE_SUBS}; do
  # Generate a placeholder email since DynamoDB records may not have email
  EMAIL="migrated-user-${USER_IDX}@tastebase.ahara.io"
  SUB_TO_EMAIL["${SUB}"]="${EMAIL}"
  USER_IDX=$((USER_IDX + 1))
done

cat >> "${OUTPUT_FILE}" <<'COMMENT'
-- =============================================================
-- JIT user creation for each unique createdBy (Cognito sub)
-- =============================================================

COMMENT

for SUB in ${UNIQUE_SUBS}; do
  EMAIL="${SUB_TO_EMAIL[${SUB}]}"
  # Escape single quotes in sub (unlikely but safe)
  SAFE_SUB=$(echo "${SUB}" | sed "s/'/''/g")
  SAFE_EMAIL=$(echo "${EMAIL}" | sed "s/'/''/g")

  cat >> "${OUTPUT_FILE}" <<EOF
-- User for Cognito sub: ${SAFE_SUB}
INSERT INTO users (id, email, display_name, created_at)
  VALUES (
    gen_random_uuid(),
    '${SAFE_EMAIL}',
    'Migrated User',
    now()
  )
  ON CONFLICT (email) DO NOTHING;

INSERT INTO cognito_users (cognito_sub, user_id, email, linked_at)
  SELECT
    '${SAFE_SUB}',
    u.id,
    '${SAFE_EMAIL}',
    now()
  FROM users u
  WHERE u.email = '${SAFE_EMAIL}'
  ON CONFLICT (cognito_sub) DO NOTHING;

EOF
done

# ---------------------------------------------------------------
# Phase 2: Insert tasting records
# ---------------------------------------------------------------
cat >> "${OUTPUT_FILE}" <<'COMMENT'
-- =============================================================
-- Tasting records
-- =============================================================

COMMENT

echo "Generating INSERT statements for ${ITEM_COUNT} tastings..."

# Use jq to generate each INSERT statement
echo "${RAW_JSON}" | jq -r '
  def sql_str: if . == null then "NULL" else . | gsub("'"'"'"; "'"'"''"'"'") | "'"'"'" + . + "'"'"'" end;
  def sql_int: if . == null then "NULL" else . end;
  def sql_bool: if . == null then "FALSE" elif . == "true" or . == true then "TRUE" else "FALSE" end;
  def sql_jsonb: if . == null then "NULL" else . | @json | gsub("'"'"'"; "'"'"''"'"'") | "'"'"'" + . + "'"'"'::jsonb" end;
  def sql_text_array:
    if . == null then "NULL"
    elif (. | type) == "array" then
      "ARRAY[" + ([.[] | if type == "object" then .S // "" else . end | gsub("'"'"'"; "'"'"''"'"'") | "'"'"'" + . + "'"'"'"] | join(",")) + "]::text[]"
    else "NULL"
    end;

  .Items[] |

  # Extract fields from DynamoDB attribute format
  {
    id:                     (.id.S // null),
    created_at:             (.createdAt.S // null),
    updated_at:             (.updatedAt.S // null),
    status:                 (.status.S // "pending"),
    product_type:           (.productType.S // null),
    name:                   (.name.S // ""),
    maker:                  (.maker.S // ""),
    date:                   (.date.S // null),
    score:                  (.score.N // null),
    style:                  (.style.S // ""),
    heat_user:              (.heatUser.N // null),
    heat_vendor:            (.heatVendor.N // null),
    refreshing:             (.refreshing.N // null),
    sweet:                  (.sweet.N // null),
    tasting_notes_user:     (.tastingNotesUser.S // ""),
    tasting_notes_vendor:   (.tastingNotesVendor.S // ""),
    product_url:            (.productUrl.S // ""),
    image_url:              (.imageUrl.S // null),
    image_key:              (.imageKey.S // null),
    ingredients_image_url:  (.ingredientsImageUrl.S // null),
    ingredients_image_key:  (.ingredientsImageKey.S // null),
    nutrition_image_url:    (.nutritionImageUrl.S // null),
    nutrition_image_key:    (.nutritionImageKey.S // null),
    nutrition_facts:        (.nutritionFacts.M // null),
    ingredients:            (if .ingredients.L then [.ingredients.L[] | .S] else null end),
    voice_key:              (.voiceKey.S // null),
    voice_transcript:       (.voiceTranscript.S // null),
    processing_error:       (.processingError.S // null),
    needs_attention:        (.needsAttention.BOOL // false),
    attention_reason:       (.attentionReason.S // null),
    created_by:             (.createdBy.S // null)
  } |

  "INSERT INTO tastings (
    id, user_id, product_type, name, maker, date, score, style,
    heat_user, heat_vendor, refreshing, sweet,
    tasting_notes_user, tasting_notes_vendor, product_url,
    image_url, image_key,
    ingredients_image_url, ingredients_image_key,
    nutrition_image_url, nutrition_image_key,
    nutrition_facts, ingredients,
    voice_key, voice_transcript,
    status, processing_error, needs_attention, attention_reason,
    created_at, updated_at
  )
  SELECT
    " + (if .id then "'" + .id + "'::uuid" else "gen_random_uuid()" end) + ",
    cu.user_id,
    " + (if .product_type then "'" + .product_type + "'::product_type" else "NULL" end) + ",
    " + (.name | sql_str) + ",
    " + (.maker | sql_str) + ",
    " + (if .date then "'" + .date + "'::date" else "CURRENT_DATE" end) + ",
    " + (.score | sql_int) + ",
    " + (.style | sql_str) + ",
    " + (.heat_user | sql_int) + ",
    " + (.heat_vendor | sql_int) + ",
    " + (.refreshing | sql_int) + ",
    " + (.sweet | sql_int) + ",
    " + (.tasting_notes_user | sql_str) + ",
    " + (.tasting_notes_vendor | sql_str) + ",
    " + (.product_url | sql_str) + ",
    " + (.image_url | sql_str) + ",
    " + (.image_key | sql_str) + ",
    " + (.ingredients_image_url | sql_str) + ",
    " + (.ingredients_image_key | sql_str) + ",
    " + (.nutrition_image_url | sql_str) + ",
    " + (.nutrition_image_key | sql_str) + ",
    " + (.nutrition_facts | sql_jsonb) + ",
    " + (.ingredients | sql_text_array) + ",
    " + (.voice_key | sql_str) + ",
    " + (.voice_transcript | sql_str) + ",
    '" + .status + "'::processing_status,
    " + (.processing_error | sql_str) + ",
    " + (.needs_attention | sql_bool) + ",
    " + (.attention_reason | sql_str) + ",
    " + (if .created_at then "'" + .created_at + "'::timestamptz" else "now()" end) + ",
    " + (if .updated_at then "'" + .updated_at + "'::timestamptz" else "now()" end) + "
  FROM cognito_users cu
  WHERE cu.cognito_sub = " + (if .created_by then "'" + .created_by + "'" else "'unknown'" end) + "
  ON CONFLICT (id) DO NOTHING;
"
' >> "${OUTPUT_FILE}"

cat >> "${OUTPUT_FILE}" <<'FOOTER'

COMMIT;
FOOTER

echo ""
echo "Migration SQL written to: ${OUTPUT_FILE}"
echo "Review the file, then run:  db-seed"
